=begin
#Upcall API

#A RESTful API (json) to manage your human-powered outbound call campaigns.

OpenAPI spec version: 2
Contact: support@upcall.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require 'spec_helper'
require 'json'

# Unit tests for Upcall::AnswersApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AnswersApi' do
  before do
    # run before each test
    @instance = Upcall::AnswersApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AnswersApi' do
    it 'should create an instance of AnswersApi' do
      expect(@instance).to be_instance_of(Upcall::AnswersApi)
    end
  end

  # unit tests for fetch_contact_answers
  # Get contact&#39;s answers
  # Fetching answers for contact
  # @param id ID of contact
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit Amount of records to return. 25 by default.
  # @option opts [Integer] :start_id Object ID to fetch next page
  # @option opts [Integer] :end_id Object ID to fetch previous page
  # @option opts [String] :result Filter. Filter collection by result
  # @option opts [String] :sort Sort field. Available fields: answer_type, created_at
  # @return [InlineResponse2005]
  describe 'fetch_contact_answers test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for fetch_question_answers
  # Get question&#39;s answers
  # Fetching answers for question
  # @param id ID of question
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit Amount of records to return. 25 by default.
  # @option opts [Integer] :start_id Object ID to fetch next page
  # @option opts [Integer] :end_id Object ID to fetch previous page
  # @option opts [String] :result Filter. Filter collection by result
  # @option opts [String] :sort Sort field. Available fields: created_at
  # @return [InlineResponse2005]
  describe 'fetch_question_answers test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
