=begin
#Upcall API

#A RESTful API (json) to manage your human-powered outbound call campaigns.

OpenAPI spec version: 2
Contact: support@upcall.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require 'spec_helper'
require 'json'

# Unit tests for Upcall::CallsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CallsApi' do
  before do
    # run before each test
    @instance = Upcall::CallsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CallsApi' do
    it 'should create an instance of CallsApi' do
      expect(@instance).to be_instance_of(Upcall::CallsApi)
    end
  end

  # unit tests for fetch_calls
  # Get all calls
  # Fetching calls for company
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit Amount of records to return. 25 by default.
  # @option opts [Integer] :start_id Object ID to fetch next page
  # @option opts [Integer] :end_id Object ID to fetch previous page
  # @option opts [String] :status Filter. Filter collection by status
  # @option opts [String] :caller_name Filter. Filter collection by caller name
  # @option opts [String] :sort Sort field. Available fields: status, called_at
  # @return [InlineResponse2004]
  describe 'fetch_calls test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for fetch_calls_for_campaign
  # Get all calls for a campaign
  # Fetching calls for campaign
  # @param id ID of campaign
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit Amount of records to return. 25 by default.
  # @option opts [Integer] :start_id Object ID to fetch next page
  # @option opts [Integer] :end_id Object ID to fetch previous page
  # @option opts [String] :status Filter. Filter collection by status
  # @option opts [String] :caller_name Filter. Filter collection by caller name
  # @option opts [String] :sort Sort field. Available fields: status, called_at
  # @return [InlineResponse2004]
  describe 'fetch_calls_for_campaign test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
