=begin
#Swagger Upcall

#A public API v2

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::CallsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CallsApi' do
  before do
    # run before each test
    @instance = SwaggerClient::CallsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CallsApi' do
    it 'should create an instact of CallsApi' do
      expect(@instance).to be_instance_of(SwaggerClient::CallsApi)
    end
  end

  # unit tests for fetch_calls
  # 
  # Fetching calls for company
  # @param authorization Authorization
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page_size Pagination. Number of items. 25 by default.
  # @option opts [Integer] :page_number Pagination. Page number. 1 by default
  # @option opts [String] :filter_status Filter. Filter collection by status
  # @option opts [String] :filter_caller_id Filter. Filter collection by caller_id
  # @option opts [String] :sort Sort field. Available fields: status, called_at
  # @return [InlineResponse2001]
  describe 'fetch_calls test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for fetch_calls_for_campaign
  # 
  # Fetching calls for campaign
  # @param authorization Authorization
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page_size Pagination. Number of items. 25 by default.
  # @option opts [Integer] :page_number Pagination. Page number. 1 by default
  # @option opts [String] :filter_status Filter. Filter collection by status
  # @option opts [String] :filter_caller_id Filter. Filter collection by caller_id
  # @option opts [String] :sort Sort field. Available fields: status, called_at
  # @return [InlineResponse2001]
  describe 'fetch_calls_for_campaign test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
