=begin
#Swagger Upcall

#A public API v2

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::ContactsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ContactsApi' do
  before do
    # run before each test
    @instance = SwaggerClient::ContactsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ContactsApi' do
    it 'should create an instact of ContactsApi' do
      expect(@instance).to be_instance_of(SwaggerClient::ContactsApi)
    end
  end

  # unit tests for create_contact
  # 
  # Create contact for campaign
  # @param authorization Authorization
  # @param campaign_id ID of campaign
  # @param contact Contact data
  # @param [Hash] opts the optional parameters
  # @return [Contact]
  describe 'create_contact test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for fetch_contacts
  # 
  # Fetching contacts for campaign
  # @param authorization Authorization
  # @param campaign_id ID of campaign
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page_size Pagination. Number of items. 25 by default.
  # @option opts [Integer] :page_number Pagination. Page number. 1 by default
  # @option opts [String] :filter_last_name Filter. Filter collection by last_name
  # @option opts [String] :filter_first_name Filter. Filter collection by first_name
  # @option opts [String] :filter_company Filter. Filter collection by company
  # @option opts [String] :filter_name Filter. Filter collection by name
  # @option opts [String] :filter_field_id Filter. Filter collection by field_id
  # @option opts [String] :filter_status Filter. Filter collection by status
  # @option opts [String] :sort Sort field. Available fields: last_name, first_name, company, calls.status                              calls.called_at, calls.caller.user.first_name, calls.caller.user.last_name
  # @return [InlineResponse200]
  describe 'fetch_contacts test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
