=begin
#Upcall API

#A RESTful API (json) to manage your human-powered outbound call campaigns.

OpenAPI spec version: 2
Contact: support@upcall.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require 'spec_helper'
require 'json'

# Unit tests for Upcall::CustomFieldsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CustomFieldsApi' do
  before do
    # run before each test
    @instance = Upcall::CustomFieldsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CustomFieldsApi' do
    it 'should create an instance of CustomFieldsApi' do
      expect(@instance).to be_instance_of(Upcall::CustomFieldsApi)
    end
  end

  # unit tests for fetch_custom_fields
  # Get custom fields
  # Fetching custom fields for contact
  # @param id ID of contact
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit Amount of records to return. 25 by default.
  # @option opts [Integer] :start_id Object ID to fetch next page
  # @option opts [Integer] :end_id Object ID to fetch previous page
  # @return [InlineResponse2006]
  describe 'fetch_custom_fields test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
