=begin
#Upcall API

#A RESTful API (json) to manage your outbound sales campaigns.

OpenAPI spec version: 2
Contact: support@upcall.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::OauthAuthorizedApplicationsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'OauthAuthorizedApplicationsApi' do
  before do
    # run before each test
    @instance = SwaggerClient::OauthAuthorizedApplicationsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of OauthAuthorizedApplicationsApi' do
    it 'should create an instact of OauthAuthorizedApplicationsApi' do
      expect(@instance).to be_instance_of(SwaggerClient::OauthAuthorizedApplicationsApi)
    end
  end

  # unit tests for fetch_oauth_authorized_applications
  # 
  # Fetch Oauth authorized applications
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse2009]
  describe 'fetch_oauth_authorized_applications test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for revoke_oauth_authorized_application
  # 
  # Revoke Oauth authorized application
  # @param id ID of authorized application
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'revoke_oauth_authorized_application test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
