=begin
#Upcall API

#A RESTful API (json) to manage your outbound sales campaigns.

OpenAPI spec version: 2
Contact: support@upcall.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::QuestionsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'QuestionsApi' do
  before do
    # run before each test
    @instance = SwaggerClient::QuestionsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of QuestionsApi' do
    it 'should create an instact of QuestionsApi' do
      expect(@instance).to be_instance_of(SwaggerClient::QuestionsApi)
    end
  end

  # unit tests for fetch_campaign_questions
  # Get campaign&#39;s questions
  # Fetching questions for campaign
  # @param id ID of campaign
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit Amount of records to return. 25 by default.
  # @option opts [Integer] :start_id Object ID to fetch next page
  # @option opts [Integer] :end_id Object ID to fetch previous page
  # @return [InlineResponse20010]
  describe 'fetch_campaign_questions test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
