=begin
#Swagger Upcall

#A public API v2

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::Call
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'Call' do
  before do
    # run before each test
    @instance = SwaggerClient::Call.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of Call' do
    it 'should create an instact of Call' do
      expect(@instance).to be_instance_of(SwaggerClient::Call)
    end
  end
  describe 'test attribute "call"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

