=begin
#Upcall API

#A RESTful API (json) to manage your outbound sales campaigns.

OpenAPI spec version: 2
Contact: support@upcall.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

# Common files
require 'swagger_client/api_client'
require 'swagger_client/api_error'
require 'swagger_client/version'
require 'swagger_client/configuration'

# Models
require 'swagger_client/models/address'
require 'swagger_client/models/answer'
require 'swagger_client/models/call'
require 'swagger_client/models/campaign'
require 'swagger_client/models/campaign_1'
require 'swagger_client/models/contact'
require 'swagger_client/models/contact_1'
require 'swagger_client/models/contact_answers'
require 'swagger_client/models/contact_attribute'
require 'swagger_client/models/error'
require 'swagger_client/models/error_errors'
require 'swagger_client/models/inline_response_200'
require 'swagger_client/models/inline_response_200_1'
require 'swagger_client/models/inline_response_200_10'
require 'swagger_client/models/inline_response_200_2'
require 'swagger_client/models/inline_response_200_3'
require 'swagger_client/models/inline_response_200_4'
require 'swagger_client/models/inline_response_200_5'
require 'swagger_client/models/inline_response_200_6'
require 'swagger_client/models/inline_response_200_7'
require 'swagger_client/models/inline_response_200_8'
require 'swagger_client/models/inline_response_200_9'
require 'swagger_client/models/keyvalue'
require 'swagger_client/models/oauth_authorized_application'
require 'swagger_client/models/question'
require 'swagger_client/models/webhook'
require 'swagger_client/models/webhook_1'

# APIs
require 'swagger_client/api/answers_api'
require 'swagger_client/api/calls_api'
require 'swagger_client/api/campaigns_api'
require 'swagger_client/api/contacts_api'
require 'swagger_client/api/custom_fields_api'
require 'swagger_client/api/oauth_authorized_applications_api'
require 'swagger_client/api/questions_api'
require 'swagger_client/api/webhooks_api'

module SwaggerClient
  class << self
    # Customize default settings for the SDK using block.
    #   SwaggerClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
