=begin
#Swagger Upcall

#A public API v2

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

# Common files
require 'swagger_client/api_client'
require 'swagger_client/api_error'
require 'swagger_client/version'
require 'swagger_client/configuration'

# Models
require 'swagger_client/models/address_default'
require 'swagger_client/models/call'
require 'swagger_client/models/call_default'
require 'swagger_client/models/contact'
require 'swagger_client/models/contact_default'
require 'swagger_client/models/contact_input'
require 'swagger_client/models/contact_input_contact'
require 'swagger_client/models/inline_response_200'
require 'swagger_client/models/inline_response_200_1'

# APIs
require 'swagger_client/api/calls_api'
require 'swagger_client/api/contacts_api'

module SwaggerClient
  class << self
    # Customize default settings for the SDK using block.
    #   SwaggerClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
